name: Build and Push kubevirt-csi-driver-operator

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # TODO brauch ich das
      # - name: Login to Quay
      #   uses: docker/login-action@v3
      #   with:
      #     registry: quay.io
      #     username: ${{ secrets.QUAY_USERNAME }}
      #     password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Build Image
        run: make docker-build
      # - name: Push Image
      #   run: make build-and-push
      #   working-directory: ${{ github.workspace }}/images/PE/
