name: release

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag"
        required: false
        default: "hubert-workflow-test"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMG: quay.io/kubermatic/kubevirt-csi-driver-operator:${{ inputs.image_tag  }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Build Image
        run: make docker-build
      - name: Push Image
        run: make docker-push
